// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NatMessage.proto

package com.qingyou.qynat.commom.protocol.proto;

public final class NatProto {
    private NatProto() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    /**
     * Protobuf enum {@code Type}
     */
    public enum Type
            implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>TYPE_NULL = 0;</code>
         */
        TYPE_NULL(0),
        /**
         * <code>REGISTER = 1;</code>
         */
        REGISTER(1),
        /**
         * <pre>
         **
         * 注册
         * </pre>
         *
         * <code>REGISTER_RESULT = 2;</code>
         */
        REGISTER_RESULT(2),
        /**
         * <pre>
         **
         * 注册
         * </pre>
         *
         * <code>CONNECTED = 3;</code>
         */
        CONNECTED(3),
        /**
         * <pre>
         **
         * 注册
         * </pre>
         *
         * <code>DISCONNECTED = 4;</code>
         */
        DISCONNECTED(4),
        /**
         * <pre>
         **
         * 注册
         * </pre>
         *
         * <code>DATA = 5;</code>
         */
        DATA(5),
        /**
         * <pre>
         **
         * 注册
         * </pre>
         *
         * <code>KEEPALIVE = 6;</code>
         */
        KEEPALIVE(6),
        UNRECOGNIZED(-1),
        ;

        /**
         * <code>TYPE_NULL = 0;</code>
         */
        public static final int TYPE_NULL_VALUE = 0;
        /**
         * <code>REGISTER = 1;</code>
         */
        public static final int REGISTER_VALUE = 1;
        /**
         * <pre>
         **
         * 注册
         * </pre>
         *
         * <code>REGISTER_RESULT = 2;</code>
         */
        public static final int REGISTER_RESULT_VALUE = 2;
        /**
         * <pre>
         **
         * 注册
         * </pre>
         *
         * <code>CONNECTED = 3;</code>
         */
        public static final int CONNECTED_VALUE = 3;
        /**
         * <pre>
         **
         * 注册
         * </pre>
         *
         * <code>DISCONNECTED = 4;</code>
         */
        public static final int DISCONNECTED_VALUE = 4;
        /**
         * <pre>
         **
         * 注册
         * </pre>
         *
         * <code>DATA = 5;</code>
         */
        public static final int DATA_VALUE = 5;
        /**
         * <pre>
         **
         * 注册
         * </pre>
         *
         * <code>KEEPALIVE = 6;</code>
         */
        public static final int KEEPALIVE_VALUE = 6;


        public final int getNumber() {
            if (this == UNRECOGNIZED) {
                throw new IllegalArgumentException(
                        "Can't get the number of an unknown enum value.");
            }
            return value;
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @Deprecated
        public static Type valueOf(int value) {
            return forNumber(value);
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         */
        public static Type forNumber(int value) {
            switch (value) {
                case 0: return TYPE_NULL;
                case 1: return REGISTER;
                case 2: return REGISTER_RESULT;
                case 3: return CONNECTED;
                case 4: return DISCONNECTED;
                case 5: return DATA;
                case 6: return KEEPALIVE;
                default: return null;
            }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
            return internalValueMap;
        }
        private static final com.google.protobuf.Internal.EnumLiteMap<
                Type> internalValueMap =
                new com.google.protobuf.Internal.EnumLiteMap<Type>() {
                    public Type findValueByNumber(int number) {
                        return Type.forNumber(number);
                    }
                };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
            if (this == UNRECOGNIZED) {
                throw new IllegalStateException(
                        "Can't get the descriptor of an unrecognized enum value.");
            }
            return getDescriptor().getValues().get(ordinal());
        }
        public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
            return getDescriptor();
        }
        public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
            return NatProto.getDescriptor().getEnumTypes().get(0);
        }

        private static final Type[] VALUES = values();

        public static Type valueOf(
                com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
            if (desc.getType() != getDescriptor()) {
                throw new IllegalArgumentException(
                        "EnumValueDescriptor is not for this type.");
            }
            if (desc.getIndex() == -1) {
                return UNRECOGNIZED;
            }
            return VALUES[desc.getIndex()];
        }

        private final int value;

        private Type(int value) {
            this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:Type)
    }

    public interface NatMessageOrBuilder extends
            // @@protoc_insertion_point(interface_extends:NatMessage)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * ID
         * </pre>
         *
         * <code>uint32 id = 1;</code>
         * @return The id.
         */
        int getId();

        /**
         * <code>map&lt;string, string&gt; meta_data = 2;</code>
         */
        int getMetaDataCount();
        /**
         * <code>map&lt;string, string&gt; meta_data = 2;</code>
         */
        boolean containsMetaData(
                String key);
        /**
         * Use {@link #getMetaDataMap()} instead.
         */
        @Deprecated
        java.util.Map<String, String>
        getMetaData();
        /**
         * <code>map&lt;string, string&gt; meta_data = 2;</code>
         */
        java.util.Map<String, String>
        getMetaDataMap();
        /**
         * <code>map&lt;string, string&gt; meta_data = 2;</code>
         */

        String getMetaDataOrDefault(
                String key,
                String defaultValue);
        /**
         * <code>map&lt;string, string&gt; meta_data = 2;</code>
         */

        String getMetaDataOrThrow(
                String key);

        /**
         * <code>.Type type = 3;</code>
         * @return The enum numeric value on the wire for type.
         */
        int getTypeValue();
        /**
         * <code>.Type type = 3;</code>
         * @return The type.
         */
        Type getType();

        /**
         * <code>bytes data = 4;</code>
         * @return The data.
         */
        com.google.protobuf.ByteString getData();
    }
    /**
     * Protobuf type {@code NatMessage}
     */
    public static final class NatMessage extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:NatMessage)
            NatMessageOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use NatMessage.newBuilder() to construct.
        private NatMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private NatMessage() {
            type_ = 0;
            data_ = com.google.protobuf.ByteString.EMPTY;
        }

        @Override
        @SuppressWarnings({"unused"})
        protected Object newInstance(
                UnusedPrivateParameter unused) {
            return new NatMessage();
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private NatMessage(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            id_ = input.readUInt32();
                            break;
                        }
                        case 18: {
                            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                                metaData_ = com.google.protobuf.MapField.newMapField(
                                        MetaDataDefaultEntryHolder.defaultEntry);
                                mutable_bitField0_ |= 0x00000001;
                            }
                            com.google.protobuf.MapEntry<String, String>
                                    metaData__ = input.readMessage(
                                    MetaDataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                            metaData_.getMutableMap().put(
                                    metaData__.getKey(), metaData__.getValue());
                            break;
                        }
                        case 24: {
                            int rawValue = input.readEnum();

                            type_ = rawValue;
                            break;
                        }
                        case 34: {

                            data_ = input.readBytes();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return NatProto.internal_static_NatMessage_descriptor;
        }

        @SuppressWarnings({"rawtypes"})
        @Override
        protected com.google.protobuf.MapField internalGetMapField(
                int number) {
            switch (number) {
                case 2:
                    return internalGetMetaData();
                default:
                    throw new RuntimeException(
                            "Invalid map field number: " + number);
            }
        }
        @Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return NatProto.internal_static_NatMessage_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            NatMessage.class, Builder.class);
        }

        public static final int ID_FIELD_NUMBER = 1;
        private int id_;
        /**
         * <pre>
         * ID
         * </pre>
         *
         * <code>uint32 id = 1;</code>
         * @return The id.
         */
        @Override
        public int getId() {
            return id_;
        }

        public static final int META_DATA_FIELD_NUMBER = 2;
        private static final class MetaDataDefaultEntryHolder {
            static final com.google.protobuf.MapEntry<
                    String, String> defaultEntry =
                    com.google.protobuf.MapEntry
                            .<String, String>newDefaultInstance(
                                    NatProto.internal_static_NatMessage_MetaDataEntry_descriptor,
                                    com.google.protobuf.WireFormat.FieldType.STRING,
                                    "",
                                    com.google.protobuf.WireFormat.FieldType.STRING,
                                    "");
        }
        private com.google.protobuf.MapField<
                String, String> metaData_;
        private com.google.protobuf.MapField<String, String>
        internalGetMetaData() {
            if (metaData_ == null) {
                return com.google.protobuf.MapField.emptyMapField(
                        MetaDataDefaultEntryHolder.defaultEntry);
            }
            return metaData_;
        }

        public int getMetaDataCount() {
            return internalGetMetaData().getMap().size();
        }
        /**
         * <code>map&lt;string, string&gt; meta_data = 2;</code>
         */

        @Override
        public boolean containsMetaData(
                String key) {
            if (key == null) { throw new NullPointerException(); }
            return internalGetMetaData().getMap().containsKey(key);
        }
        /**
         * Use {@link #getMetaDataMap()} instead.
         */
        @Override
        @Deprecated
        public java.util.Map<String, String> getMetaData() {
            return getMetaDataMap();
        }
        /**
         * <code>map&lt;string, string&gt; meta_data = 2;</code>
         */
        @Override

        public java.util.Map<String, String> getMetaDataMap() {
            return internalGetMetaData().getMap();
        }
        /**
         * <code>map&lt;string, string&gt; meta_data = 2;</code>
         */
        @Override

        public String getMetaDataOrDefault(
                String key,
                String defaultValue) {
            if (key == null) { throw new NullPointerException(); }
            java.util.Map<String, String> map =
                    internalGetMetaData().getMap();
            return map.containsKey(key) ? map.get(key) : defaultValue;
        }
        /**
         * <code>map&lt;string, string&gt; meta_data = 2;</code>
         */
        @Override

        public String getMetaDataOrThrow(
                String key) {
            if (key == null) { throw new NullPointerException(); }
            java.util.Map<String, String> map =
                    internalGetMetaData().getMap();
            if (!map.containsKey(key)) {
                throw new IllegalArgumentException();
            }
            return map.get(key);
        }

        public static final int TYPE_FIELD_NUMBER = 3;
        private int type_;
        /**
         * <code>.Type type = 3;</code>
         * @return The enum numeric value on the wire for type.
         */
        @Override public int getTypeValue() {
            return type_;
        }
        /**
         * <code>.Type type = 3;</code>
         * @return The type.
         */
        @Override public Type getType() {
            @SuppressWarnings("deprecation")
            Type result = Type.valueOf(type_);
            return result == null ? Type.UNRECOGNIZED : result;
        }

        public static final int DATA_FIELD_NUMBER = 4;
        private com.google.protobuf.ByteString data_;
        /**
         * <code>bytes data = 4;</code>
         * @return The data.
         */
        @Override
        public com.google.protobuf.ByteString getData() {
            return data_;
        }

        private byte memoizedIsInitialized = -1;
        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (id_ != 0) {
                output.writeUInt32(1, id_);
            }
            com.google.protobuf.GeneratedMessageV3
                    .serializeStringMapTo(
                            output,
                            internalGetMetaData(),
                            MetaDataDefaultEntryHolder.defaultEntry,
                            2);
            if (type_ != Type.TYPE_NULL.getNumber()) {
                output.writeEnum(3, type_);
            }
            if (!data_.isEmpty()) {
                output.writeBytes(4, data_);
            }
            unknownFields.writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (id_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(1, id_);
            }
            for (java.util.Map.Entry<String, String> entry
                    : internalGetMetaData().getMap().entrySet()) {
                com.google.protobuf.MapEntry<String, String>
                        metaData__ = MetaDataDefaultEntryHolder.defaultEntry.newBuilderForType()
                        .setKey(entry.getKey())
                        .setValue(entry.getValue())
                        .build();
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(2, metaData__);
            }
            if (type_ != Type.TYPE_NULL.getNumber()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(3, type_);
            }
            if (!data_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(4, data_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof NatMessage)) {
                return super.equals(obj);
            }
            NatMessage other = (NatMessage) obj;

            if (getId()
                    != other.getId()) return false;
            if (!internalGetMetaData().equals(
                    other.internalGetMetaData())) return false;
            if (type_ != other.type_) return false;
            if (!getData()
                    .equals(other.getData())) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + ID_FIELD_NUMBER;
            hash = (53 * hash) + getId();
            if (!internalGetMetaData().getMap().isEmpty()) {
                hash = (37 * hash) + META_DATA_FIELD_NUMBER;
                hash = (53 * hash) + internalGetMetaData().hashCode();
            }
            hash = (37 * hash) + TYPE_FIELD_NUMBER;
            hash = (53 * hash) + type_;
            hash = (37 * hash) + DATA_FIELD_NUMBER;
            hash = (53 * hash) + getData().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static NatMessage parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static NatMessage parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static NatMessage parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static NatMessage parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static NatMessage parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static NatMessage parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static NatMessage parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static NatMessage parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static NatMessage parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static NatMessage parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static NatMessage parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static NatMessage parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(NatMessage prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code NatMessage}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:NatMessage)
                NatMessageOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return NatProto.internal_static_NatMessage_descriptor;
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMapField(
                    int number) {
                switch (number) {
                    case 2:
                        return internalGetMetaData();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }
            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMutableMapField(
                    int number) {
                switch (number) {
                    case 2:
                        return internalGetMutableMetaData();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }
            @Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return NatProto.internal_static_NatMessage_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                NatMessage.class, Builder.class);
            }

            // Construct using com.qingyou.qynat.commom.protocol.proto.NatProto.NatMessage.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            @Override
            public Builder clear() {
                super.clear();
                id_ = 0;

                internalGetMutableMetaData().clear();
                type_ = 0;

                data_ = com.google.protobuf.ByteString.EMPTY;

                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return NatProto.internal_static_NatMessage_descriptor;
            }

            @Override
            public NatMessage getDefaultInstanceForType() {
                return NatMessage.getDefaultInstance();
            }

            @Override
            public NatMessage build() {
                NatMessage result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public NatMessage buildPartial() {
                NatMessage result = new NatMessage(this);
                int from_bitField0_ = bitField0_;
                result.id_ = id_;
                result.metaData_ = internalGetMetaData();
                result.metaData_.makeImmutable();
                result.type_ = type_;
                result.data_ = data_;
                onBuilt();
                return result;
            }

            @Override
            public Builder clone() {
                return super.clone();
            }
            @Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.setField(field, value);
            }
            @Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }
            @Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }
            @Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return super.setRepeatedField(field, index, value);
            }
            @Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.addRepeatedField(field, value);
            }
            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof NatMessage) {
                    return mergeFrom((NatMessage)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(NatMessage other) {
                if (other == NatMessage.getDefaultInstance()) return this;
                if (other.getId() != 0) {
                    setId(other.getId());
                }
                internalGetMutableMetaData().mergeFrom(
                        other.internalGetMetaData());
                if (other.type_ != 0) {
                    setTypeValue(other.getTypeValue());
                }
                if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
                    setData(other.getData());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                NatMessage parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (NatMessage) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            private int bitField0_;

            private int id_ ;
            /**
             * <pre>
             * ID
             * </pre>
             *
             * <code>uint32 id = 1;</code>
             * @return The id.
             */
            @Override
            public int getId() {
                return id_;
            }
            /**
             * <pre>
             * ID
             * </pre>
             *
             * <code>uint32 id = 1;</code>
             * @param value The id to set.
             * @return This builder for chaining.
             */
            public Builder setId(int value) {

                id_ = value;
                onChanged();
                return this;
            }
            /**
             * <pre>
             * ID
             * </pre>
             *
             * <code>uint32 id = 1;</code>
             * @return This builder for chaining.
             */
            public Builder clearId() {

                id_ = 0;
                onChanged();
                return this;
            }

            private com.google.protobuf.MapField<
                    String, String> metaData_;
            private com.google.protobuf.MapField<String, String>
            internalGetMetaData() {
                if (metaData_ == null) {
                    return com.google.protobuf.MapField.emptyMapField(
                            MetaDataDefaultEntryHolder.defaultEntry);
                }
                return metaData_;
            }
            private com.google.protobuf.MapField<String, String>
            internalGetMutableMetaData() {
                onChanged();;
                if (metaData_ == null) {
                    metaData_ = com.google.protobuf.MapField.newMapField(
                            MetaDataDefaultEntryHolder.defaultEntry);
                }
                if (!metaData_.isMutable()) {
                    metaData_ = metaData_.copy();
                }
                return metaData_;
            }

            public int getMetaDataCount() {
                return internalGetMetaData().getMap().size();
            }
            /**
             * <code>map&lt;string, string&gt; meta_data = 2;</code>
             */

            @Override
            public boolean containsMetaData(
                    String key) {
                if (key == null) { throw new NullPointerException(); }
                return internalGetMetaData().getMap().containsKey(key);
            }
            /**
             * Use {@link #getMetaDataMap()} instead.
             */
            @Override
            @Deprecated
            public java.util.Map<String, String> getMetaData() {
                return getMetaDataMap();
            }
            /**
             * <code>map&lt;string, string&gt; meta_data = 2;</code>
             */
            @Override

            public java.util.Map<String, String> getMetaDataMap() {
                return internalGetMetaData().getMap();
            }
            /**
             * <code>map&lt;string, string&gt; meta_data = 2;</code>
             */
            @Override

            public String getMetaDataOrDefault(
                    String key,
                    String defaultValue) {
                if (key == null) { throw new NullPointerException(); }
                java.util.Map<String, String> map =
                        internalGetMetaData().getMap();
                return map.containsKey(key) ? map.get(key) : defaultValue;
            }
            /**
             * <code>map&lt;string, string&gt; meta_data = 2;</code>
             */
            @Override

            public String getMetaDataOrThrow(
                    String key) {
                if (key == null) { throw new NullPointerException(); }
                java.util.Map<String, String> map =
                        internalGetMetaData().getMap();
                if (!map.containsKey(key)) {
                    throw new IllegalArgumentException();
                }
                return map.get(key);
            }

            public Builder clearMetaData() {
                internalGetMutableMetaData().getMutableMap()
                        .clear();
                return this;
            }
            /**
             * <code>map&lt;string, string&gt; meta_data = 2;</code>
             */

            public Builder removeMetaData(
                    String key) {
                if (key == null) { throw new NullPointerException(); }
                internalGetMutableMetaData().getMutableMap()
                        .remove(key);
                return this;
            }
            /**
             * Use alternate mutation accessors instead.
             */
            @Deprecated
            public java.util.Map<String, String>
            getMutableMetaData() {
                return internalGetMutableMetaData().getMutableMap();
            }
            /**
             * <code>map&lt;string, string&gt; meta_data = 2;</code>
             */
            public Builder putMetaData(
                    String key,
                    String value) {
                if (key == null) { throw new NullPointerException(); }
                if (value == null) { throw new NullPointerException(); }
                internalGetMutableMetaData().getMutableMap()
                        .put(key, value);
                return this;
            }
            /**
             * <code>map&lt;string, string&gt; meta_data = 2;</code>
             */

            public Builder putAllMetaData(
                    java.util.Map<String, String> values) {
                internalGetMutableMetaData().getMutableMap()
                        .putAll(values);
                return this;
            }

            private int type_ = 0;
            /**
             * <code>.Type type = 3;</code>
             * @return The enum numeric value on the wire for type.
             */
            @Override public int getTypeValue() {
                return type_;
            }
            /**
             * <code>.Type type = 3;</code>
             * @param value The enum numeric value on the wire for type to set.
             * @return This builder for chaining.
             */
            public Builder setTypeValue(int value) {

                type_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>.Type type = 3;</code>
             * @return The type.
             */
            @Override
            public Type getType() {
                @SuppressWarnings("deprecation")
                Type result = Type.valueOf(type_);
                return result == null ? Type.UNRECOGNIZED : result;
            }
            /**
             * <code>.Type type = 3;</code>
             * @param value The type to set.
             * @return This builder for chaining.
             */
            public Builder setType(Type value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                type_ = value.getNumber();
                onChanged();
                return this;
            }
            /**
             * <code>.Type type = 3;</code>
             * @return This builder for chaining.
             */
            public Builder clearType() {

                type_ = 0;
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
            /**
             * <code>bytes data = 4;</code>
             * @return The data.
             */
            @Override
            public com.google.protobuf.ByteString getData() {
                return data_;
            }
            /**
             * <code>bytes data = 4;</code>
             * @param value The data to set.
             * @return This builder for chaining.
             */
            public Builder setData(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                data_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>bytes data = 4;</code>
             * @return This builder for chaining.
             */
            public Builder clearData() {

                data_ = getDefaultInstance().getData();
                onChanged();
                return this;
            }
            @Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:NatMessage)
        }

        // @@protoc_insertion_point(class_scope:NatMessage)
        private static final NatMessage DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new NatMessage();
        }

        public static NatMessage getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<NatMessage>
                PARSER = new com.google.protobuf.AbstractParser<NatMessage>() {
            @Override
            public NatMessage parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new NatMessage(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<NatMessage> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<NatMessage> getParserForType() {
            return PARSER;
        }

        @Override
        public NatMessage getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_NatMessage_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_NatMessage_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_NatMessage_MetaDataEntry_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_NatMessage_MetaDataEntry_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        String[] descriptorData = {
                "\n\020NatMessage.proto\"\232\001\n\nNatMessage\022\n\n\002id\030" +
                        "\001 \001(\r\022,\n\tmeta_data\030\002 \003(\0132\031.NatMessage.Me" +
                        "taDataEntry\022\023\n\004type\030\003 \001(\0162\005.Type\022\014\n\004data" +
                        "\030\004 \001(\014\032/\n\rMetaDataEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005" +
                        "value\030\002 \001(\t:\0028\001*r\n\004Type\022\r\n\tTYPE_NULL\020\000\022\014" +
                        "\n\010REGISTER\020\001\022\023\n\017REGISTER_RESULT\020\002\022\r\n\tCON" +
                        "NECTED\020\003\022\020\n\014DISCONNECTED\020\004\022\010\n\004DATA\020\005\022\r\n\t" +
                        "KEEPALIVE\020\006B-\n!com.qingyou.qynat.commom." +
                        "protocolB\010NatProtob\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        });
        internal_static_NatMessage_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_NatMessage_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_NatMessage_descriptor,
                new String[] { "Id", "MetaData", "Type", "Data", });
        internal_static_NatMessage_MetaDataEntry_descriptor =
                internal_static_NatMessage_descriptor.getNestedTypes().get(0);
        internal_static_NatMessage_MetaDataEntry_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_NatMessage_MetaDataEntry_descriptor,
                new String[] { "Key", "Value", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
